### ISSUE TITLE
Open for integration with Jupyter Book and GitHub pages?

### ISSUE THREAD

**Issue by SimonBiggs** [openregulatory/templates#11]
I don't want to bring in unwanted scope creep here, and if it's not something you're keen on, I'd be more than okay with that. Nevertheless, I thought I'd ask, would you be open if I made a PR that rendered this repo with [Jupyter Book](https://jupyterbook.org/en/stable/intro.html) and GitHub pages?

**Comment by SimonBiggs** [comment]
If there's interest, here is what it looks like with currently very minimal changes to the templates, with all of them pulled in, as they are at the moment:

https://docs.radiotherapy.ai/

**Comment by olieidel** [comment]
Hi @SimonBiggs, thanks for that suggestion! :) And sorry for my super-late reply.

Hm, as a software engineer, I think it could make sense; but as OpenRegulatory dude I think it wouldn't provide much value in addition to the HTML-rendered templates we also provide on our [templates page](https://openregulatory.com/templates/) (scroll down on [this page](https://openregulatory.com/intended-use-medical-devices-mdd-mdr-template/) for an example).

It would literally be duplicate content. So I'd prefer not to do it, unfortunately.

Hope you understand!

**Comment by SimonBiggs** [comment]
> Hope you understand!

Completely :) I did suspect it might make this repo quite a bit more complicated that what it needed to be.
